// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	DB: KVNamespace;
	HEDERA_NODE_API_URL: "https://testnet.mirrornode.hedera.com";
	APP_PUB_KEY: "0.0.5234801";
	AES_ECB_KEY: "b4d26ed3a4b2cffb66429bbc093f3a8f225a39759d4f361ae53950b50f3b9eb4";
}
