// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	DB: KVNamespace;
	HEDERA_NODE_API_URL: "https://testnet.mirrornode.hedera.com";
	APP_PUB_KEY: "0.0.5234801";
	AES_ECB_KEY: "";
}
